# Generated by Django 4.2.3 on 2023-07-23 20:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('matchName', models.CharField(max_length=100)),
                ('endResult', models.CharField(max_length=10)),
            ],
        ),
    ]
